language: node_js
node_js:
 - "node"
before_install:
  - npm install -g codecov istanbul mocha chai request express
script:
   - mocha ./test/*_test.js
   - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
   - codecov
deploy:
  provider: heroku
  api_key:
    secure: 5f9beea9-adce-48c4-8820-20f6f011fde1
  app: node-test-kaizen
  on:
    repo: kaizen-c/node99js
