language: node_js
node_js:
 - "node"
before_install:
  - npm install -g codecov istanbul mocha chai request express
script:
 # - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
 # - codecov
   - cd ./test
   - ls
   - mocha *_test.js
   - istanbul cover _mocha
   - bash <(curl -s https://codecov.io/bash)